variables:
  ODOO_PROD_URL:
    source: ODOO_PROD_URL
  ODOO_PROD_DB:
    source: ODOO_PROD_DB
  ODOO_PROD_USERNAME:
    source: ODOO_PROD_USERNAME
  ODOO_PROD_PASSWORD:
    source: ODOO_PROD_PASSWORD

validation:
  required:
    - ODOO_PROD_URL
    - ODOO_PROD_DB
    - ODOO_PROD_USERNAME
    - ODOO_PROD_PASSWORD
